### PR TITLE
Fix as suggested in https://github.com/uBlockOrigin/uMatrix-issues/is…

### PR DESCRIPTION
**Pull request by uBlock-user**
@gorhill

### CODE REVIEW

**Comment by gwarser** [comment]
No checks for pre 72? Re: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/vYIaeezZwfQ

**Comment by uBlock-user** [comment]
I didn't add any checks, if that's what you mean, just the required header for uMatrix to get COOKIE blocking and REFERRER blocking functionality back.

**Comment by gorhill** [comment]
It's fixed on my side since yesterday. You can't just add `extraHeaders` like this, you have to check for version.

**Comment by uBlock-user** [comment]
> It's fixed on my side since yesterday

How ? It affects all the dev builds of Chromium.

**Comment by gorhill** [comment]
"Fixed on my side" means I already have the fix locally. I didn't immediately commit/tag a new build because it's on top of another fix, and I wanted to test more. Just adding `extraHeaders` breaks Chromium pre-72 (first thing I checked) and possibly Firefox. However I revised the fix to use the approach from the Chromium dev pointed above by @gwarser, I was testing using `vAPI.webextFlavor` -- which works fine but I prefer the officially suggested approach.

**Comment by uBlock-user** [comment]
Does this affect uBlock too ? Lets say I have a scriptlet thats designed for not sending cookies, would it work without extraHeaders in uBO ?

**Pull request closed without merging**
