### PR TITLE
Update Permissions link with correct link

### PR DESCRIPTION
**Pull request by uBlock-user**
Corrected for all the rest of the locales

### CODE REVIEW

**Comment by uBlock-user** [comment]
I don't know that as I don't use Crowdin.

**Comment by xofe** [comment]
Unless they're also submitted at Crowdin, then yes, they would be overwritten.

**Comment by uBlock-user** [comment]
I first did it for the [`en`](https://github.com/gorhill/uMatrix/pull/997) locale, but not for the rest, so I decided to finish doing the rest too fyi

**Comment by uBlock-user** [comment]
Closing it since you're getting them all from Crowdin.

**Pull request closed without merging**
