### PR TITLE
If GitHub issues is for bugs, why is GitHub issues disabled?

### PR DESCRIPTION
**Pull request by CrazyPython**
I created a fake, empty pull request with one empty commit to contact you about this.

### CODE REVIEW

**Comment by gorhill** [comment]
As said in my last comment on the last invalid issue opened, I am closing it temporary because of repeated invalid issues opened with complete disregard to CONTRIBUTING. It's my time being abused.

**Comment by CrazyPython** [comment]
@gorhill create a separate repository for issues and crowdsource people to tag valid issues, perhaps?

**Comment by thomas-gardner** [comment]
Hi @gorhill, how then can people view the old issues for this repo? I am trying to access 'Incompatibility with Vimperator · Issue #228' but it keeps returning 404s.

**Comment by gcbw** [comment]
As someone who was guilty of opening a duplicate issue, in my defense the original did not have any good searchable terms. In the end, dups are annoying but they help to prevent dups later on since they add new terms.

maybe adding someone else as an admin?

**Comment by uBlock-user** [comment]
As long as there's an issue tracker, duplicates, invalid and irrelevant issues are bound to be opened by people, that's a universal problem with the system, even Chromium's issue tracker is filled with such nonsense. So either you can disable issue tracker for good, and have zero annoyance or keep it open and indulge yourself as they keep coming. There's no true solution for this.

**Comment by dcousens** [comment]
@gorhill what if others could help with the filtering and only tag you in issues that met the criteria?

**Comment by TriMoon** [comment]
This is just a sign that @gorhill will abondon this project and leave it to die...
What other **acceptable** reason would there be to deny bug reporting on  **public** project?
Maybe someone should fork this project and manage it better...

@gorhill , I know you hate bug reports this way so here is another one:

- Your [web extension version 1.0.1b1](https://github.com/gorhill/uMatrix/releases/tag/1.0.1b1) is not able to present any configuration or log window using Firefox Nightly 55.0a1 (2017-06-05) (64-bit)

**Comment by gorhill** [comment]
> Your web extension version 1.0.1b1 is not able to present any configuration or log window.

https://bugzilla.mozilla.org/show_bug.cgi?id=1271354

**Comment by gorhill** [comment]
> This is just a sign that @gorhill will abondon this project and leave it to die...
> What other **acceptable** reason would there be to deny bug reporting on  **public** project?
> Maybe someone should fork this project and manage it better...

Unfortunately, forced to lock this issue because of the trolling.

**Pull request closed without merging**
